### ISSUE TITLE
Stuck after logging in via Github - the Getting Started page from the website doesn't redirect to New Chat after authentication.

### ISSUE THREAD

**Issue by srishti-56** [potpie-ai/potpie#155]
Description
The Getting Started flow from the website doesn't redirect to the new chat/actionable page for potpie. I've already installed potpie on 2 repositories. When I was actually a new user, this worked. So it's only for returning users. 
Ideally, as a user I should have clicked the Sign In button, but Getting Started was more intuitive since I hadn't actually 'used' Potpie after installing it. 

Steps to Reproduce
1. Install potpie on Github/add repository
2. Click Getting Started on the website. 
3. Login with the same Github account
4. Takes you to Integrations tab with Potpie open/installed.
5. Does not redirect to New Chat/actionable flow for user.

Let me know if you'd like any additional details added!

<img width="1101" alt="image" src="https://github.com/user-attachments/assets/e4967b2b-8aac-4091-b045-8ba0e1ff8262">

**Comment by dhirenmathur** [comment]
@srishti-56 Thanks for reporting this! 
@vineetshar can you take a look at the Github app settings please.

**Comment by dhirenmathur** [comment]
Hey @srishti-56 this was an issue on the UI, we fixed this a couple days back, can you try again? Thanks!

**Comment by srishti-56** [comment]
Hmm, just checked, it still doesn't redirect to the chat page

**Comment by dhirenmathur** [comment]
@srishti-56 can you confirm whether it worked so that I can close the issue?

**Comment by srishti-56** [comment]
i changed the selected repository (deleted one of them) it redirected back to the 'Continue with Github' page..to clarify, this page doesn't appear -
<img width="1117" alt="image" src="https://github.com/user-attachments/assets/b692687b-e2e7-4968-a091-dea79b221f73">
